name: Docker Image CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dist: [ v3.13, v3.14, v3.15, edge ]
        arch: [ x86_64, armhf, armv7, aarch64 ]

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Build Docker Image (${{ matrix.arch }})
        run: |
          docker build . \
            --build-arg ARCH=${{ matrix.arch }} \
            --build-arg DIST=${{ matrix.dist }}
