name: Docker Image Build and Deploy
on:
  push:
    tags: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dist: [ v3.15, v3.16, v3.17, edge ]
        arch: [ x86_64, armhf, armv7, aarch64 ]
        include:
          - arch: x86_64
            platform: linux/amd64

          - arch: armhf
            platform: linux/arm/v6

          - arch: armv7
            platform: linux/arm/v7

          - arch: aarch64
            platform: linux/arm64

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      
      - uses: docker/setup-buildx-action@v3

      - uses: crazy-max/ghaction-docker-meta@v1
        id: docker_meta
        with:
          images: asymworks/alpine-abuild-${{ matrix.arch }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: |
            ARCH=${{ matrix.arch }}
            DIST=${{ matrix.dist }}
          tags: asymworks/alpine-abuild-${{matrix.arch}}:${{ matrix.dist }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Push image to GHCR
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/asymworks/alpine-abuild-${{matrix.arch}}:${{ matrix.dist }} \
            asymworks/alpine-abuild-${{matrix.arch}}:${{ matrix.dist }}
